name: ros-example
version: 1.0
summary: A robot example
icon: icon.svg
description: A really small ROS example

apps:
  rosmaster:
    command: bin/roscore-rosmaster-service
    daemon: simple
    uses: [listener]
  listener:
    command: rosrun beginner_tutorials listener
    uses: [listener]
  talker:
    command: rosrun beginner_tutorials talker
    uses: [listener]

uses:
  listener:
    type: migration-skill
    caps: [network-listener]

parts:
  catkin-tutorials:
    plugin: catkin
    source: .
    catkin-packages:
      - beginner_tutorials
