name: snapcraft
summary: easily create snaps
description: |
    Snapcraft aims to make upstream developers' lives easier and as such is not
    a single toolset, but instead is a collection of tools that enable the
    natural workflow of an upstream to be extended with a simple release step
    into Snappy.
adopt-info: snapcraft
confinement: classic

apps:
  snapcraft:
    command: bin/snapcraft
    completer: snapcraft-completion

build-packages:
  - build-essential
  - libapt-pkg-dev
  - libffi-dev
  - libssl-dev
  - libsodium-dev
  - liblzma-dev
  - libyaml-dev
  - patch
  - sed

parts:
  bash-completion:
    source: debian
    plugin: dump
    stage:
      - snapcraft-completion
  snapcraft:
    source: .
    plugin: python
    requirements: requirements.txt
    stage-packages: &stage-packages
        - apt
        - apt-transport-https
        - apt-utils
        - binutils
        - execstack
        - gpgv
        - libffi6
        - libsodium18
        - patchelf
        - squashfs-tools
        - xdelta3
    organize:
        # Put snapcraftctl into its own directory that can be included in the PATH
        # without including other binaries.
        bin/snapcraftctl: bin/scriptlet-bin/snapcraftctl
    override-pull: |
        snapcraftctl pull
        version="$(git describe --dirty --always | sed -e 's/-/+git/;y/-/./')"
        [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
        snapcraftctl set-version "$version"
        snapcraftctl set-grade "$grade"
    override-build: |
        snapcraftctl build
        ./tools/snapcraft-override-build.sh

  legacy-snapcraft:
    plugin: python
    source: https://github.com/kyrofa/snapcraft.git
    source-branch: feature/refactor_override_build
    source-depth: 1
    requirements: requirements.txt
    stage-packages: *stage-packages
    override-build: |
        snapcraftctl build
        ./tools/snapcraft-override-build.sh

        sed -ri 's|(lib/.*/site-packages)|legacy_snapcraft/\1|' $SNAPCRAFT_PART_INSTALL/usr/lib/python3.5/sitecustomize.py
    organize:
        '*': legacy_snapcraft/
